// Package schedule provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package schedule

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ScheduledDayReason.
const (
	ScheduledDayReasonAssignedOff ScheduledDayReason = "assigned_off"
	ScheduledDayReasonDefault     ScheduledDayReason = "default"
	ScheduledDayReasonHoliday     ScheduledDayReason = "holiday"
	ScheduledDayReasonNotAWorkday ScheduledDayReason = "not_a_workday"
	ScheduledDayReasonShift       ScheduledDayReason = "shift"
)

// Valid indicates whether the value is a known member of the ScheduledDayReason enum.
func (e ScheduledDayReason) Valid() bool {
	switch e {
	case ScheduledDayReasonAssignedOff:
		return true
	case ScheduledDayReasonDefault:
		return true
	case ScheduledDayReasonHoliday:
		return true
	case ScheduledDayReasonNotAWorkday:
		return true
	case ScheduledDayReasonShift:
		return true
	default:
		return false
	}
}

// AssignShiftsRequest defines model for AssignShiftsRequest.
type AssignShiftsRequest struct {
	Assignments []ShiftAssignmentRequest `json:"assignments"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Holiday defines model for Holiday.
type Holiday struct {
	Date openapi_types.Date `json:"date"`
	Id   int64              `json:"id"`
	Name string             `json:"name"`
}

// HolidayRequest defines model for HolidayRequest.
type HolidayRequest struct {
	Date openapi_types.Date `json:"date"`

	// Name Example: Hari Kemerdekaan
	Name string `json:"name"`
}

// OfficeLocation defines model for OfficeLocation.
type OfficeLocation struct {
	Id      int64   `json:"id"`
	Lat     float64 `json:"lat"`
	Lng     float64 `json:"lng"`
	Name    string  `json:"name"`
	RadiusM int     `json:"radius_m"`
}

// OfficeLocationRequest defines model for OfficeLocationRequest.
type OfficeLocationRequest struct {
	// Lat Example: -6.2088
	Lat float64 `json:"lat"`

	// Lng Example: 106.8456
	Lng float64 `json:"lng"`

	// Name Example: Kantor Pusat
	Name string `json:"name"`

	// RadiusM 10 to 10000 metres.
	//
	// Example: 100
	RadiusM int `json:"radius_m"`
}

// ScheduledDay defines model for ScheduledDay.
type ScheduledDay struct {
	Date openapi_types.Date `json:"date"`

	// HolidayName Set whenever a holiday falls on the date, whether the schedule observes it or not.
	HolidayName *string `json:"holiday_name,omitempty"`

	// Reason Why the day is or is not worked: shift (the roster names a schedule), default (the
	// caller's own schedule covers this weekday), assigned_off (the roster names no schedule),
	// holiday (a holiday the schedule observes), not_a_workday (anything else).
	Reason   ScheduledDayReason `json:"reason"`
	Schedule *WorkSchedule      `json:"schedule,omitempty"`
	Working  bool               `json:"working"`
}

// ScheduledDayReason Why the day is or is not worked: shift (the roster names a schedule), default (the
// caller's own schedule covers this weekday), assigned_off (the roster names no schedule),
// holiday (a holiday the schedule observes), not_a_workday (anything else).
type ScheduledDayReason string

// ShiftAssignment defines model for ShiftAssignment.
type ShiftAssignment struct {
	Id   *int64  `json:"id,omitempty"`
	Note *string `json:"note,omitempty"`

	// ScheduleId Null is a planned day off.
	ScheduleId *int64             `json:"schedule_id,omitempty"`
	UserId     int64              `json:"user_id"`
	WorkDate   openapi_types.Date `json:"work_date"`
}

// ShiftAssignmentRequest defines model for ShiftAssignmentRequest.
type ShiftAssignmentRequest struct {
	// Note At most 200 characters.
	Note *string `json:"note,omitempty"`

	// ScheduleId Leave out or send null for a planned day off.
	ScheduleId *int64             `json:"schedule_id,omitempty"`
	UserId     int64              `json:"user_id"`
	WorkDate   openapi_types.Date `json:"work_date"`
}

// WorkSchedule defines model for WorkSchedule.
type WorkSchedule struct {
	BreakMinutes int `json:"break_minutes"`

	// CrossesMidnight Derived from the two times, never stored, so they cannot disagree.
	CrossesMidnight bool `json:"crosses_midnight"`

	// EndTime Example: 17:00
	EndTime          string `json:"end_time"`
	GraceMinutes     int    `json:"grace_minutes"`
	Id               int64  `json:"id"`
	Name             string `json:"name"`
	ObservesHolidays bool   `json:"observes_holidays"`

	// StartTime Example: 08:00
	StartTime string `json:"start_time"`
	Workdays  []int  `json:"workdays"`
}

// WorkScheduleRequest defines model for WorkScheduleRequest.
type WorkScheduleRequest struct {
	// BreakMinutes Unpaid break, 0 to 480, and shorter than the shift. Defaults to 0.
	//
	// Example: 60
	BreakMinutes *int `json:"break_minutes,omitempty"`

	// EndTime Example: 06:00
	EndTime string `json:"end_time"`

	// GraceMinutes Minutes of lateness still counted as on time, 0 to 240. Defaults to 0.
	//
	// Example: 15
	GraceMinutes *int `json:"grace_minutes,omitempty"`

	// Name Example: Shift Malam
	Name string `json:"name"`

	// ObservesHolidays Whether a public holiday turns this schedule off. Defaults to false.
	ObservesHolidays *bool `json:"observes_holidays,omitempty"`

	// StartTime HH:MM or HH:MM:SS. An end at or before the start means the shift crosses midnight.
	//
	// Example: 22:00
	StartTime string `json:"start_time"`

	// Workdays ISO weekdays, 1 (Monday) to 7 (Sunday).
	//
	// Example: [1,2,3,4,5]
	Workdays []int `json:"workdays"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListHolidaysParams defines parameters for ListHolidays.
type ListHolidaysParams struct {
	From openapi_types.Date `form:"from" json:"from"`

	// To Inclusive, and at most 366 days after from.
	To openapi_types.Date `form:"to" json:"to"`
}

// GetMyScheduleParams defines parameters for GetMySchedule.
type GetMyScheduleParams struct {
	From openapi_types.Date `form:"from" json:"from"`

	// To Inclusive, and at most 366 days after from.
	To openapi_types.Date `form:"to" json:"to"`
}

// ListShiftAssignmentsParams defines parameters for ListShiftAssignments.
type ListShiftAssignmentsParams struct {
	From openapi_types.Date `form:"from" json:"from"`

	// To Inclusive, and at most 366 days after from.
	To openapi_types.Date `form:"to" json:"to"`

	// UserId Only this person's roster.
	UserId *int64 `form:"user_id,omitempty" json:"user_id,omitempty"`
}

// CreateHolidayJSONRequestBody defines body for CreateHoliday for application/json ContentType.
type CreateHolidayJSONRequestBody = HolidayRequest

// UpdateHolidayJSONRequestBody defines body for UpdateHoliday for application/json ContentType.
type UpdateHolidayJSONRequestBody = HolidayRequest

// CreateOfficeLocationJSONRequestBody defines body for CreateOfficeLocation for application/json ContentType.
type CreateOfficeLocationJSONRequestBody = OfficeLocationRequest

// UpdateOfficeLocationJSONRequestBody defines body for UpdateOfficeLocation for application/json ContentType.
type UpdateOfficeLocationJSONRequestBody = OfficeLocationRequest

// AssignShiftsJSONRequestBody defines body for AssignShifts for application/json ContentType.
type AssignShiftsJSONRequestBody = AssignShiftsRequest

// CreateWorkScheduleJSONRequestBody defines body for CreateWorkSchedule for application/json ContentType.
type CreateWorkScheduleJSONRequestBody = WorkScheduleRequest

// UpdateWorkScheduleJSONRequestBody defines body for UpdateWorkSchedule for application/json ContentType.
type UpdateWorkScheduleJSONRequestBody = WorkScheduleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListHolidays List public holidays in a span
	// (GET /holidays)
	ListHolidays(c *gin.Context, params ListHolidaysParams)
	// CreateHoliday Add a public holiday
	// (POST /holidays)
	CreateHoliday(c *gin.Context)
	// DeleteHoliday Remove a public holiday
	// (DELETE /holidays/{id})
	DeleteHoliday(c *gin.Context, id int64)
	// UpdateHoliday Replace a public holiday
	// (PUT /holidays/{id})
	UpdateHoliday(c *gin.Context, id int64)
	// GetMySchedule Get the caller's working days
	// (GET /me/schedule)
	GetMySchedule(c *gin.Context, params GetMyScheduleParams)
	// ListOfficeLocations List office locations
	// (GET /office-locations)
	ListOfficeLocations(c *gin.Context)
	// CreateOfficeLocation Add an office location
	// (POST /office-locations)
	CreateOfficeLocation(c *gin.Context)
	// DeleteOfficeLocation Remove an office location
	// (DELETE /office-locations/{id})
	DeleteOfficeLocation(c *gin.Context, id int64)
	// UpdateOfficeLocation Replace an office location
	// (PUT /office-locations/{id})
	UpdateOfficeLocation(c *gin.Context, id int64)
	// ListShiftAssignments List the roster for a span
	// (GET /shift-assignments)
	ListShiftAssignments(c *gin.Context, params ListShiftAssignmentsParams)
	// AssignShifts Write a batch of roster
	// (POST /shift-assignments)
	AssignShifts(c *gin.Context)
	// DeleteShiftAssignment Remove a roster entry
	// (DELETE /shift-assignments/{id})
	DeleteShiftAssignment(c *gin.Context, id int64)
	// ListWorkSchedules List work schedules
	// (GET /work-schedules)
	ListWorkSchedules(c *gin.Context)
	// CreateWorkSchedule Add a work schedule
	// (POST /work-schedules)
	CreateWorkSchedule(c *gin.Context)
	// DeleteWorkSchedule Remove a work schedule
	// (DELETE /work-schedules/{id})
	DeleteWorkSchedule(c *gin.Context, id int64)
	// UpdateWorkSchedule Replace a work schedule
	// (PUT /work-schedules/{id})
	UpdateWorkSchedule(c *gin.Context, id int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListHolidays operation middleware
func (siw *ServerInterfaceWrapper) ListHolidays(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListHolidaysParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListHolidays(c, params)
}

// CreateHoliday operation middleware
func (siw *ServerInterfaceWrapper) CreateHoliday(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateHoliday(c)
}

// DeleteHoliday operation middleware
func (siw *ServerInterfaceWrapper) DeleteHoliday(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteHoliday(c, id)
}

// UpdateHoliday operation middleware
func (siw *ServerInterfaceWrapper) UpdateHoliday(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateHoliday(c, id)
}

// GetMySchedule operation middleware
func (siw *ServerInterfaceWrapper) GetMySchedule(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMyScheduleParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMySchedule(c, params)
}

// ListOfficeLocations operation middleware
func (siw *ServerInterfaceWrapper) ListOfficeLocations(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListOfficeLocations(c)
}

// CreateOfficeLocation operation middleware
func (siw *ServerInterfaceWrapper) CreateOfficeLocation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateOfficeLocation(c)
}

// DeleteOfficeLocation operation middleware
func (siw *ServerInterfaceWrapper) DeleteOfficeLocation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteOfficeLocation(c, id)
}

// UpdateOfficeLocation operation middleware
func (siw *ServerInterfaceWrapper) UpdateOfficeLocation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateOfficeLocation(c, id)
}

// ListShiftAssignments operation middleware
func (siw *ServerInterfaceWrapper) ListShiftAssignments(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListShiftAssignmentsParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListShiftAssignments(c, params)
}

// AssignShifts operation middleware
func (siw *ServerInterfaceWrapper) AssignShifts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AssignShifts(c)
}

// DeleteShiftAssignment operation middleware
func (siw *ServerInterfaceWrapper) DeleteShiftAssignment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteShiftAssignment(c, id)
}

// ListWorkSchedules operation middleware
func (siw *ServerInterfaceWrapper) ListWorkSchedules(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListWorkSchedules(c)
}

// CreateWorkSchedule operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkSchedule(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateWorkSchedule(c)
}

// DeleteWorkSchedule operation middleware
func (siw *ServerInterfaceWrapper) DeleteWorkSchedule(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteWorkSchedule(c, id)
}

// UpdateWorkSchedule operation middleware
func (siw *ServerInterfaceWrapper) UpdateWorkSchedule(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateWorkSchedule(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me/schedule", wrapper.GetMySchedule)
	router.GET(options.BaseURL+"/work-schedules", wrapper.ListWorkSchedules)
	router.POST(options.BaseURL+"/work-schedules", wrapper.CreateWorkSchedule)
	router.DELETE(options.BaseURL+"/work-schedules/:id", wrapper.DeleteWorkSchedule)
	router.PUT(options.BaseURL+"/work-schedules/:id", wrapper.UpdateWorkSchedule)
	router.GET(options.BaseURL+"/holidays", wrapper.ListHolidays)
	router.POST(options.BaseURL+"/holidays", wrapper.CreateHoliday)
	router.DELETE(options.BaseURL+"/holidays/:id", wrapper.DeleteHoliday)
	router.PUT(options.BaseURL+"/holidays/:id", wrapper.UpdateHoliday)
	router.GET(options.BaseURL+"/office-locations", wrapper.ListOfficeLocations)
	router.POST(options.BaseURL+"/office-locations", wrapper.CreateOfficeLocation)
	router.DELETE(options.BaseURL+"/office-locations/:id", wrapper.DeleteOfficeLocation)
	router.PUT(options.BaseURL+"/office-locations/:id", wrapper.UpdateOfficeLocation)
	router.GET(options.BaseURL+"/shift-assignments", wrapper.ListShiftAssignments)
	router.POST(options.BaseURL+"/shift-assignments", wrapper.AssignShifts)
	router.DELETE(options.BaseURL+"/shift-assignments/:id", wrapper.DeleteShiftAssignment)
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListHolidaysRequestObject struct {
	Params ListHolidaysParams
}

type ListHolidaysResponseObject interface {
	VisitListHolidaysResponse(w http.ResponseWriter) error
}

type ListHolidays200JSONResponse []Holiday

func (response ListHolidays200JSONResponse) VisitListHolidaysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListHolidays400JSONResponse struct{ BadRequestJSONResponse }

func (response ListHolidays400JSONResponse) VisitListHolidaysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListHolidays401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListHolidays401JSONResponse) VisitListHolidaysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListHolidays403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListHolidays403JSONResponse) VisitListHolidaysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateHolidayRequestObject struct {
	Body *CreateHolidayJSONRequestBody
}

type CreateHolidayResponseObject interface {
	VisitCreateHolidayResponse(w http.ResponseWriter) error
}

type CreateHoliday201JSONResponse Holiday

func (response CreateHoliday201JSONResponse) VisitCreateHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateHoliday400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateHoliday400JSONResponse) VisitCreateHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateHoliday401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateHoliday401JSONResponse) VisitCreateHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateHoliday403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateHoliday403JSONResponse) VisitCreateHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateHoliday409JSONResponse struct{ ConflictJSONResponse }

func (response CreateHoliday409JSONResponse) VisitCreateHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteHolidayRequestObject struct {
	Id int64 `json:"id"`
}

type DeleteHolidayResponseObject interface {
	VisitDeleteHolidayResponse(w http.ResponseWriter) error
}

type DeleteHoliday204Response struct {
}

func (response DeleteHoliday204Response) VisitDeleteHolidayResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteHoliday401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteHoliday401JSONResponse) VisitDeleteHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteHoliday403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteHoliday403JSONResponse) VisitDeleteHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteHoliday404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteHoliday404JSONResponse) VisitDeleteHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateHolidayRequestObject struct {
	Id   int64 `json:"id"`
	Body *UpdateHolidayJSONRequestBody
}

type UpdateHolidayResponseObject interface {
	VisitUpdateHolidayResponse(w http.ResponseWriter) error
}

type UpdateHoliday200JSONResponse Holiday

func (response UpdateHoliday200JSONResponse) VisitUpdateHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateHoliday400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateHoliday400JSONResponse) VisitUpdateHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateHoliday401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateHoliday401JSONResponse) VisitUpdateHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateHoliday403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateHoliday403JSONResponse) VisitUpdateHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateHoliday404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateHoliday404JSONResponse) VisitUpdateHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateHoliday409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateHoliday409JSONResponse) VisitUpdateHolidayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetMyScheduleRequestObject struct {
	Params GetMyScheduleParams
}

type GetMyScheduleResponseObject interface {
	VisitGetMyScheduleResponse(w http.ResponseWriter) error
}

type GetMySchedule200JSONResponse []ScheduledDay

func (response GetMySchedule200JSONResponse) VisitGetMyScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMySchedule400JSONResponse struct{ BadRequestJSONResponse }

func (response GetMySchedule400JSONResponse) VisitGetMyScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMySchedule401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMySchedule401JSONResponse) VisitGetMyScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMySchedule404JSONResponse struct{ NotFoundJSONResponse }

func (response GetMySchedule404JSONResponse) VisitGetMyScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListOfficeLocationsRequestObject struct {
}

type ListOfficeLocationsResponseObject interface {
	VisitListOfficeLocationsResponse(w http.ResponseWriter) error
}

type ListOfficeLocations200JSONResponse []OfficeLocation

func (response ListOfficeLocations200JSONResponse) VisitListOfficeLocationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListOfficeLocations401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListOfficeLocations401JSONResponse) VisitListOfficeLocationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListOfficeLocations403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListOfficeLocations403JSONResponse) VisitListOfficeLocationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOfficeLocationRequestObject struct {
	Body *CreateOfficeLocationJSONRequestBody
}

type CreateOfficeLocationResponseObject interface {
	VisitCreateOfficeLocationResponse(w http.ResponseWriter) error
}

type CreateOfficeLocation201JSONResponse OfficeLocation

func (response CreateOfficeLocation201JSONResponse) VisitCreateOfficeLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOfficeLocation400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateOfficeLocation400JSONResponse) VisitCreateOfficeLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOfficeLocation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateOfficeLocation401JSONResponse) VisitCreateOfficeLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOfficeLocation403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateOfficeLocation403JSONResponse) VisitCreateOfficeLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOfficeLocationRequestObject struct {
	Id int64 `json:"id"`
}

type DeleteOfficeLocationResponseObject interface {
	VisitDeleteOfficeLocationResponse(w http.ResponseWriter) error
}

type DeleteOfficeLocation204Response struct {
}

func (response DeleteOfficeLocation204Response) VisitDeleteOfficeLocationResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteOfficeLocation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteOfficeLocation401JSONResponse) VisitDeleteOfficeLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOfficeLocation403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteOfficeLocation403JSONResponse) VisitDeleteOfficeLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOfficeLocation404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteOfficeLocation404JSONResponse) VisitDeleteOfficeLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOfficeLocationRequestObject struct {
	Id   int64 `json:"id"`
	Body *UpdateOfficeLocationJSONRequestBody
}

type UpdateOfficeLocationResponseObject interface {
	VisitUpdateOfficeLocationResponse(w http.ResponseWriter) error
}

type UpdateOfficeLocation200JSONResponse OfficeLocation

func (response UpdateOfficeLocation200JSONResponse) VisitUpdateOfficeLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOfficeLocation400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateOfficeLocation400JSONResponse) VisitUpdateOfficeLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOfficeLocation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateOfficeLocation401JSONResponse) VisitUpdateOfficeLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOfficeLocation403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateOfficeLocation403JSONResponse) VisitUpdateOfficeLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOfficeLocation404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateOfficeLocation404JSONResponse) VisitUpdateOfficeLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListShiftAssignmentsRequestObject struct {
	Params ListShiftAssignmentsParams
}

type ListShiftAssignmentsResponseObject interface {
	VisitListShiftAssignmentsResponse(w http.ResponseWriter) error
}

type ListShiftAssignments200JSONResponse []ShiftAssignment

func (response ListShiftAssignments200JSONResponse) VisitListShiftAssignmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListShiftAssignments400JSONResponse struct{ BadRequestJSONResponse }

func (response ListShiftAssignments400JSONResponse) VisitListShiftAssignmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListShiftAssignments401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListShiftAssignments401JSONResponse) VisitListShiftAssignmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListShiftAssignments403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListShiftAssignments403JSONResponse) VisitListShiftAssignmentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AssignShiftsRequestObject struct {
	Body *AssignShiftsJSONRequestBody
}

type AssignShiftsResponseObject interface {
	VisitAssignShiftsResponse(w http.ResponseWriter) error
}

type AssignShifts200JSONResponse []ShiftAssignment

func (response AssignShifts200JSONResponse) VisitAssignShiftsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AssignShifts400JSONResponse struct{ BadRequestJSONResponse }

func (response AssignShifts400JSONResponse) VisitAssignShiftsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AssignShifts401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AssignShifts401JSONResponse) VisitAssignShiftsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AssignShifts403JSONResponse struct{ ForbiddenJSONResponse }

func (response AssignShifts403JSONResponse) VisitAssignShiftsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteShiftAssignmentRequestObject struct {
	Id int64 `json:"id"`
}

type DeleteShiftAssignmentResponseObject interface {
	VisitDeleteShiftAssignmentResponse(w http.ResponseWriter) error
}

type DeleteShiftAssignment204Response struct {
}

func (response DeleteShiftAssignment204Response) VisitDeleteShiftAssignmentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteShiftAssignment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteShiftAssignment401JSONResponse) VisitDeleteShiftAssignmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteShiftAssignment403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteShiftAssignment403JSONResponse) VisitDeleteShiftAssignmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteShiftAssignment404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteShiftAssignment404JSONResponse) VisitDeleteShiftAssignmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListWorkSchedulesRequestObject struct {
}

type ListWorkSchedulesResponseObject interface {
	VisitListWorkSchedulesResponse(w http.ResponseWriter) error
}

type ListWorkSchedules200JSONResponse []WorkSchedule

func (response ListWorkSchedules200JSONResponse) VisitListWorkSchedulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListWorkSchedules401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListWorkSchedules401JSONResponse) VisitListWorkSchedulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListWorkSchedules403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListWorkSchedules403JSONResponse) VisitListWorkSchedulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWorkScheduleRequestObject struct {
	Body *CreateWorkScheduleJSONRequestBody
}

type CreateWorkScheduleResponseObject interface {
	VisitCreateWorkScheduleResponse(w http.ResponseWriter) error
}

type CreateWorkSchedule201JSONResponse WorkSchedule

func (response CreateWorkSchedule201JSONResponse) VisitCreateWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWorkSchedule400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateWorkSchedule400JSONResponse) VisitCreateWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWorkSchedule401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateWorkSchedule401JSONResponse) VisitCreateWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWorkSchedule403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateWorkSchedule403JSONResponse) VisitCreateWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteWorkScheduleRequestObject struct {
	Id int64 `json:"id"`
}

type DeleteWorkScheduleResponseObject interface {
	VisitDeleteWorkScheduleResponse(w http.ResponseWriter) error
}

type DeleteWorkSchedule204Response struct {
}

func (response DeleteWorkSchedule204Response) VisitDeleteWorkScheduleResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteWorkSchedule401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteWorkSchedule401JSONResponse) VisitDeleteWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteWorkSchedule403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteWorkSchedule403JSONResponse) VisitDeleteWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteWorkSchedule404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteWorkSchedule404JSONResponse) VisitDeleteWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteWorkSchedule409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteWorkSchedule409JSONResponse) VisitDeleteWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateWorkScheduleRequestObject struct {
	Id   int64 `json:"id"`
	Body *UpdateWorkScheduleJSONRequestBody
}

type UpdateWorkScheduleResponseObject interface {
	VisitUpdateWorkScheduleResponse(w http.ResponseWriter) error
}

type UpdateWorkSchedule200JSONResponse WorkSchedule

func (response UpdateWorkSchedule200JSONResponse) VisitUpdateWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateWorkSchedule400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateWorkSchedule400JSONResponse) VisitUpdateWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateWorkSchedule401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateWorkSchedule401JSONResponse) VisitUpdateWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateWorkSchedule403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateWorkSchedule403JSONResponse) VisitUpdateWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateWorkSchedule404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateWorkSchedule404JSONResponse) VisitUpdateWorkScheduleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListHolidays List public holidays in a span
	// (GET /holidays)
	ListHolidays(ctx context.Context, request ListHolidaysRequestObject) (ListHolidaysResponseObject, error)
	// CreateHoliday Add a public holiday
	// (POST /holidays)
	CreateHoliday(ctx context.Context, request CreateHolidayRequestObject) (CreateHolidayResponseObject, error)
	// DeleteHoliday Remove a public holiday
	// (DELETE /holidays/{id})
	DeleteHoliday(ctx context.Context, request DeleteHolidayRequestObject) (DeleteHolidayResponseObject, error)
	// UpdateHoliday Replace a public holiday
	// (PUT /holidays/{id})
	UpdateHoliday(ctx context.Context, request UpdateHolidayRequestObject) (UpdateHolidayResponseObject, error)
	// GetMySchedule Get the caller's working days
	// (GET /me/schedule)
	GetMySchedule(ctx context.Context, request GetMyScheduleRequestObject) (GetMyScheduleResponseObject, error)
	// ListOfficeLocations List office locations
	// (GET /office-locations)
	ListOfficeLocations(ctx context.Context, request ListOfficeLocationsRequestObject) (ListOfficeLocationsResponseObject, error)
	// CreateOfficeLocation Add an office location
	// (POST /office-locations)
	CreateOfficeLocation(ctx context.Context, request CreateOfficeLocationRequestObject) (CreateOfficeLocationResponseObject, error)
	// DeleteOfficeLocation Remove an office location
	// (DELETE /office-locations/{id})
	DeleteOfficeLocation(ctx context.Context, request DeleteOfficeLocationRequestObject) (DeleteOfficeLocationResponseObject, error)
	// UpdateOfficeLocation Replace an office location
	// (PUT /office-locations/{id})
	UpdateOfficeLocation(ctx context.Context, request UpdateOfficeLocationRequestObject) (UpdateOfficeLocationResponseObject, error)
	// ListShiftAssignments List the roster for a span
	// (GET /shift-assignments)
	ListShiftAssignments(ctx context.Context, request ListShiftAssignmentsRequestObject) (ListShiftAssignmentsResponseObject, error)
	// AssignShifts Write a batch of roster
	// (POST /shift-assignments)
	AssignShifts(ctx context.Context, request AssignShiftsRequestObject) (AssignShiftsResponseObject, error)
	// DeleteShiftAssignment Remove a roster entry
	// (DELETE /shift-assignments/{id})
	DeleteShiftAssignment(ctx context.Context, request DeleteShiftAssignmentRequestObject) (DeleteShiftAssignmentResponseObject, error)
	// ListWorkSchedules List work schedules
	// (GET /work-schedules)
	ListWorkSchedules(ctx context.Context, request ListWorkSchedulesRequestObject) (ListWorkSchedulesResponseObject, error)
	// CreateWorkSchedule Add a work schedule
	// (POST /work-schedules)
	CreateWorkSchedule(ctx context.Context, request CreateWorkScheduleRequestObject) (CreateWorkScheduleResponseObject, error)
	// DeleteWorkSchedule Remove a work schedule
	// (DELETE /work-schedules/{id})
	DeleteWorkSchedule(ctx context.Context, request DeleteWorkScheduleRequestObject) (DeleteWorkScheduleResponseObject, error)
	// UpdateWorkSchedule Replace a work schedule
	// (PUT /work-schedules/{id})
	UpdateWorkSchedule(ctx context.Context, request UpdateWorkScheduleRequestObject) (UpdateWorkScheduleResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ListHolidays operation middleware
func (sh *strictHandler) ListHolidays(ctx *gin.Context, params ListHolidaysParams) {
	var request ListHolidaysRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListHolidays(ctx, request.(ListHolidaysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListHolidays")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListHolidaysResponseObject); ok {
		if err := validResponse.VisitListHolidaysResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateHoliday operation middleware
func (sh *strictHandler) CreateHoliday(ctx *gin.Context) {
	var request CreateHolidayRequestObject

	var body CreateHolidayJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateHoliday(ctx, request.(CreateHolidayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateHoliday")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateHolidayResponseObject); ok {
		if err := validResponse.VisitCreateHolidayResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteHoliday operation middleware
func (sh *strictHandler) DeleteHoliday(ctx *gin.Context, id int64) {
	var request DeleteHolidayRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteHoliday(ctx, request.(DeleteHolidayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteHoliday")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteHolidayResponseObject); ok {
		if err := validResponse.VisitDeleteHolidayResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateHoliday operation middleware
func (sh *strictHandler) UpdateHoliday(ctx *gin.Context, id int64) {
	var request UpdateHolidayRequestObject

	request.Id = id

	var body UpdateHolidayJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateHoliday(ctx, request.(UpdateHolidayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateHoliday")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateHolidayResponseObject); ok {
		if err := validResponse.VisitUpdateHolidayResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMySchedule operation middleware
func (sh *strictHandler) GetMySchedule(ctx *gin.Context, params GetMyScheduleParams) {
	var request GetMyScheduleRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMySchedule(ctx, request.(GetMyScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMySchedule")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetMyScheduleResponseObject); ok {
		if err := validResponse.VisitGetMyScheduleResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListOfficeLocations operation middleware
func (sh *strictHandler) ListOfficeLocations(ctx *gin.Context) {
	var request ListOfficeLocationsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListOfficeLocations(ctx, request.(ListOfficeLocationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOfficeLocations")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListOfficeLocationsResponseObject); ok {
		if err := validResponse.VisitListOfficeLocationsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOfficeLocation operation middleware
func (sh *strictHandler) CreateOfficeLocation(ctx *gin.Context) {
	var request CreateOfficeLocationRequestObject

	var body CreateOfficeLocationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOfficeLocation(ctx, request.(CreateOfficeLocationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOfficeLocation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateOfficeLocationResponseObject); ok {
		if err := validResponse.VisitCreateOfficeLocationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOfficeLocation operation middleware
func (sh *strictHandler) DeleteOfficeLocation(ctx *gin.Context, id int64) {
	var request DeleteOfficeLocationRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOfficeLocation(ctx, request.(DeleteOfficeLocationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOfficeLocation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteOfficeLocationResponseObject); ok {
		if err := validResponse.VisitDeleteOfficeLocationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateOfficeLocation operation middleware
func (sh *strictHandler) UpdateOfficeLocation(ctx *gin.Context, id int64) {
	var request UpdateOfficeLocationRequestObject

	request.Id = id

	var body UpdateOfficeLocationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateOfficeLocation(ctx, request.(UpdateOfficeLocationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateOfficeLocation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateOfficeLocationResponseObject); ok {
		if err := validResponse.VisitUpdateOfficeLocationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListShiftAssignments operation middleware
func (sh *strictHandler) ListShiftAssignments(ctx *gin.Context, params ListShiftAssignmentsParams) {
	var request ListShiftAssignmentsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListShiftAssignments(ctx, request.(ListShiftAssignmentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListShiftAssignments")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListShiftAssignmentsResponseObject); ok {
		if err := validResponse.VisitListShiftAssignmentsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AssignShifts operation middleware
func (sh *strictHandler) AssignShifts(ctx *gin.Context) {
	var request AssignShiftsRequestObject

	var body AssignShiftsJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AssignShifts(ctx, request.(AssignShiftsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AssignShifts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AssignShiftsResponseObject); ok {
		if err := validResponse.VisitAssignShiftsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteShiftAssignment operation middleware
func (sh *strictHandler) DeleteShiftAssignment(ctx *gin.Context, id int64) {
	var request DeleteShiftAssignmentRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteShiftAssignment(ctx, request.(DeleteShiftAssignmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteShiftAssignment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteShiftAssignmentResponseObject); ok {
		if err := validResponse.VisitDeleteShiftAssignmentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListWorkSchedules operation middleware
func (sh *strictHandler) ListWorkSchedules(ctx *gin.Context) {
	var request ListWorkSchedulesRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListWorkSchedules(ctx, request.(ListWorkSchedulesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListWorkSchedules")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListWorkSchedulesResponseObject); ok {
		if err := validResponse.VisitListWorkSchedulesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateWorkSchedule operation middleware
func (sh *strictHandler) CreateWorkSchedule(ctx *gin.Context) {
	var request CreateWorkScheduleRequestObject

	var body CreateWorkScheduleJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateWorkSchedule(ctx, request.(CreateWorkScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateWorkSchedule")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateWorkScheduleResponseObject); ok {
		if err := validResponse.VisitCreateWorkScheduleResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteWorkSchedule operation middleware
func (sh *strictHandler) DeleteWorkSchedule(ctx *gin.Context, id int64) {
	var request DeleteWorkScheduleRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteWorkSchedule(ctx, request.(DeleteWorkScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteWorkSchedule")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteWorkScheduleResponseObject); ok {
		if err := validResponse.VisitDeleteWorkScheduleResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateWorkSchedule operation middleware
func (sh *strictHandler) UpdateWorkSchedule(ctx *gin.Context, id int64) {
	var request UpdateWorkScheduleRequestObject

	request.Id = id

	var body UpdateWorkScheduleJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateWorkSchedule(ctx, request.(UpdateWorkScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateWorkSchedule")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateWorkScheduleResponseObject); ok {
		if err := validResponse.VisitUpdateWorkScheduleResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
