// Package report provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package report

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Status.
const (
	Absent  Status = "absent"
	Holiday Status = "holiday"
	Late    Status = "late"
	NotYet  Status = "not_yet"
	Off     Status = "off"
	OnLeave Status = "on_leave"
	Present Status = "present"
)

// Valid indicates whether the value is a known member of the Status enum.
func (e Status) Valid() bool {
	switch e {
	case Absent:
		return true
	case Holiday:
		return true
	case Late:
		return true
	case NotYet:
		return true
	case Off:
		return true
	case OnLeave:
		return true
	case Present:
		return true
	default:
		return false
	}
}

// AttendanceReport defines model for AttendanceReport.
type AttendanceReport struct {
	Days []ReportDay        `json:"days"`
	From openapi_types.Date `json:"from"`

	// People One per person with at least one day listed, in the same order.
	People []ReportTotal      `json:"people"`
	To     openapi_types.Date `json:"to"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// ReportDay defines model for ReportDay.
type ReportDay struct {
	CheckInAt         *time.Time `json:"check_in_at,omitempty"`
	CheckOutAt        *time.Time `json:"check_out_at,omitempty"`
	DepartmentId      *int64     `json:"department_id,omitempty"`
	EarlyLeaveMinutes int        `json:"early_leave_minutes"`
	FullName          string     `json:"full_name"`
	LateMinutes       int        `json:"late_minutes"`

	// Status present or late with an attendance; otherwise on_leave (approved leave covers the date), holiday, off
	// (not a working day), not_yet (the shift and its grace have not started), or absent.
	Status   Status             `json:"status"`
	UserId   int64              `json:"user_id"`
	WorkDate openapi_types.Date `json:"work_date"`

	// WorkedMinutes Whole minutes from check-in to check-out, breaks included; 0 until checked out.
	WorkedMinutes int `json:"worked_minutes"`
}

// ReportTotal defines model for ReportTotal.
type ReportTotal struct {
	Absent       int    `json:"absent"`
	DepartmentId *int64 `json:"department_id,omitempty"`
	FullName     string `json:"full_name"`

	// Late Days checked in late.
	Late    int `json:"late"`
	OnLeave int `json:"on_leave"`

	// Present Days checked in on time.
	Present       int   `json:"present"`
	UserId        int64 `json:"user_id"`
	WorkedMinutes int   `json:"worked_minutes"`
}

// Status present or late with an attendance; otherwise on_leave (approved leave covers the date), holiday, off
// (not a working day), not_yet (the shift and its grace have not started), or absent.
type Status string

// DepartmentID defines model for DepartmentID.
type DepartmentID = int64

// From defines model for From.
type From = openapi_types.Date

// To defines model for To.
type To = openapi_types.Date

// UserID defines model for UserID.
type UserID = int64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetAttendanceReportParams defines parameters for GetAttendanceReport.
type GetAttendanceReportParams struct {
	From From `form:"from" json:"from"`

	// To Inclusive; at most 366 days after from.
	To           To            `form:"to" json:"to"`
	UserId       *UserID       `form:"user_id,omitempty" json:"user_id,omitempty"`
	DepartmentId *DepartmentID `form:"department_id,omitempty" json:"department_id,omitempty"`

	// Status Only the days with this status; the totals then count those days alone.
	Status *Status `form:"status,omitempty" json:"status,omitempty"`
}

// GetAttendanceReportCsvParams defines parameters for GetAttendanceReportCsv.
type GetAttendanceReportCsvParams struct {
	From From `form:"from" json:"from"`

	// To Inclusive; at most 366 days after from.
	To           To            `form:"to" json:"to"`
	UserId       *UserID       `form:"user_id,omitempty" json:"user_id,omitempty"`
	DepartmentId *DepartmentID `form:"department_id,omitempty" json:"department_id,omitempty"`

	// Status Only the days with this status; the totals then count those days alone.
	Status *Status `form:"status,omitempty" json:"status,omitempty"`
}

// GetAttendanceReportPdfParams defines parameters for GetAttendanceReportPdf.
type GetAttendanceReportPdfParams struct {
	From From `form:"from" json:"from"`

	// To Inclusive; at most 366 days after from.
	To           To            `form:"to" json:"to"`
	UserId       *UserID       `form:"user_id,omitempty" json:"user_id,omitempty"`
	DepartmentId *DepartmentID `form:"department_id,omitempty" json:"department_id,omitempty"`

	// Status Only the days with this status; the totals then count those days alone.
	Status *Status `form:"status,omitempty" json:"status,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAttendanceReport Daily statuses and per-person totals over a range
	// (GET /reports/attendance)
	GetAttendanceReport(c *gin.Context, params GetAttendanceReportParams)
	// GetAttendanceReportCsv The report's days as CSV
	// (GET /reports/attendance.csv)
	GetAttendanceReportCsv(c *gin.Context, params GetAttendanceReportCsvParams)
	// GetAttendanceReportPdf The report's per-person totals as a PDF
	// (GET /reports/attendance.pdf)
	GetAttendanceReportPdf(c *gin.Context, params GetAttendanceReportPdfParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAttendanceReport operation middleware
func (siw *ServerInterfaceWrapper) GetAttendanceReport(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAttendanceReportParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "department_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "department_id", c.Request.URL.Query(), &params.DepartmentId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter department_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAttendanceReport(c, params)
}

// GetAttendanceReportCsv operation middleware
func (siw *ServerInterfaceWrapper) GetAttendanceReportCsv(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAttendanceReportCsvParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "department_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "department_id", c.Request.URL.Query(), &params.DepartmentId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter department_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAttendanceReportCsv(c, params)
}

// GetAttendanceReportPdf operation middleware
func (siw *ServerInterfaceWrapper) GetAttendanceReportPdf(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAttendanceReportPdfParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", c.Request.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "department_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "department_id", c.Request.URL.Query(), &params.DepartmentId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter department_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAttendanceReportPdf(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/reports/attendance", wrapper.GetAttendanceReport)
	router.GET(options.BaseURL+"/reports/attendance.csv", wrapper.GetAttendanceReportCsv)
	router.GET(options.BaseURL+"/reports/attendance.pdf", wrapper.GetAttendanceReportPdf)
}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type UnauthorizedJSONResponse Error

type GetAttendanceReportRequestObject struct {
	Params GetAttendanceReportParams
}

type GetAttendanceReportResponseObject interface {
	VisitGetAttendanceReportResponse(w http.ResponseWriter) error
}

type GetAttendanceReport200JSONResponse AttendanceReport

func (response GetAttendanceReport200JSONResponse) VisitGetAttendanceReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceReport400JSONResponse struct{ BadRequestJSONResponse }

func (response GetAttendanceReport400JSONResponse) VisitGetAttendanceReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceReport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAttendanceReport401JSONResponse) VisitGetAttendanceReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceReport403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAttendanceReport403JSONResponse) VisitGetAttendanceReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceReportCsvRequestObject struct {
	Params GetAttendanceReportCsvParams
}

type GetAttendanceReportCsvResponseObject interface {
	VisitGetAttendanceReportCsvResponse(w http.ResponseWriter) error
}

type GetAttendanceReportCsv200ResponseHeaders struct {
	ContentDisposition string
}

type GetAttendanceReportCsv200TextcsvResponse struct {
	Body          io.Reader
	Headers       GetAttendanceReportCsv200ResponseHeaders
	ContentLength int64
}

func (response GetAttendanceReportCsv200TextcsvResponse) VisitGetAttendanceReportCsvResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/csv")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetAttendanceReportCsv400JSONResponse struct{ BadRequestJSONResponse }

func (response GetAttendanceReportCsv400JSONResponse) VisitGetAttendanceReportCsvResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceReportCsv401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAttendanceReportCsv401JSONResponse) VisitGetAttendanceReportCsvResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceReportCsv403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAttendanceReportCsv403JSONResponse) VisitGetAttendanceReportCsvResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceReportPdfRequestObject struct {
	Params GetAttendanceReportPdfParams
}

type GetAttendanceReportPdfResponseObject interface {
	VisitGetAttendanceReportPdfResponse(w http.ResponseWriter) error
}

type GetAttendanceReportPdf200ResponseHeaders struct {
	ContentDisposition string
}

type GetAttendanceReportPdf200ApplicationpdfResponse struct {
	Body          io.Reader
	Headers       GetAttendanceReportPdf200ResponseHeaders
	ContentLength int64
}

func (response GetAttendanceReportPdf200ApplicationpdfResponse) VisitGetAttendanceReportPdfResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/pdf")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetAttendanceReportPdf400JSONResponse struct{ BadRequestJSONResponse }

func (response GetAttendanceReportPdf400JSONResponse) VisitGetAttendanceReportPdfResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceReportPdf401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAttendanceReportPdf401JSONResponse) VisitGetAttendanceReportPdfResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendanceReportPdf403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAttendanceReportPdf403JSONResponse) VisitGetAttendanceReportPdfResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetAttendanceReport Daily statuses and per-person totals over a range
	// (GET /reports/attendance)
	GetAttendanceReport(ctx context.Context, request GetAttendanceReportRequestObject) (GetAttendanceReportResponseObject, error)
	// GetAttendanceReportCsv The report's days as CSV
	// (GET /reports/attendance.csv)
	GetAttendanceReportCsv(ctx context.Context, request GetAttendanceReportCsvRequestObject) (GetAttendanceReportCsvResponseObject, error)
	// GetAttendanceReportPdf The report's per-person totals as a PDF
	// (GET /reports/attendance.pdf)
	GetAttendanceReportPdf(ctx context.Context, request GetAttendanceReportPdfRequestObject) (GetAttendanceReportPdfResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetAttendanceReport operation middleware
func (sh *strictHandler) GetAttendanceReport(ctx *gin.Context, params GetAttendanceReportParams) {
	var request GetAttendanceReportRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAttendanceReport(ctx, request.(GetAttendanceReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAttendanceReport")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAttendanceReportResponseObject); ok {
		if err := validResponse.VisitGetAttendanceReportResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAttendanceReportCsv operation middleware
func (sh *strictHandler) GetAttendanceReportCsv(ctx *gin.Context, params GetAttendanceReportCsvParams) {
	var request GetAttendanceReportCsvRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAttendanceReportCsv(ctx, request.(GetAttendanceReportCsvRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAttendanceReportCsv")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAttendanceReportCsvResponseObject); ok {
		if err := validResponse.VisitGetAttendanceReportCsvResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAttendanceReportPdf operation middleware
func (sh *strictHandler) GetAttendanceReportPdf(ctx *gin.Context, params GetAttendanceReportPdfParams) {
	var request GetAttendanceReportPdfRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAttendanceReportPdf(ctx, request.(GetAttendanceReportPdfRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAttendanceReportPdf")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAttendanceReportPdfResponseObject); ok {
		if err := validResponse.VisitGetAttendanceReportPdfResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
