// Package upload provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package upload

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
)

// Defines values for UploadIntentRequestPurpose.
const (
	AttendancePhoto UploadIntentRequestPurpose = "attendance_photo"
	LeaveAttachment UploadIntentRequestPurpose = "leave_attachment"
)

// Valid indicates whether the value is a known member of the UploadIntentRequestPurpose enum.
func (e UploadIntentRequestPurpose) Valid() bool {
	switch e {
	case AttendancePhoto:
		return true
	case LeaveAttachment:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// UploadIntent defines model for UploadIntent.
type UploadIntent struct {
	ExpiresAt time.Time `json:"expires_at"`

	// Headers Headers the PUT must carry, exactly as given; they are part of the signature.
	//
	// Example: {"Content-Type":"image/jpeg","If-None-Match":"*"}
	Headers map[string]string `json:"headers"`
	Key     string            `json:"key"`
	Url     string            `json:"url"`
}

// UploadIntentRequest defines model for UploadIntentRequest.
type UploadIntentRequest struct {
	// ContentType Example: image/jpeg
	ContentType string                     `json:"content_type"`
	Purpose     UploadIntentRequestPurpose `json:"purpose"`

	// SizeBytes Example: 204800
	SizeBytes int64 `json:"size_bytes"`
}

// UploadIntentRequestPurpose defines model for UploadIntentRequest.Purpose.
type UploadIntentRequestPurpose string

// CreateUploadIntentJSONRequestBody defines body for CreateUploadIntent for application/json ContentType.
type CreateUploadIntentJSONRequestBody = UploadIntentRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateUploadIntent Create an upload intent
	// (POST /uploads/intent)
	CreateUploadIntent(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateUploadIntent operation middleware
func (siw *ServerInterfaceWrapper) CreateUploadIntent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateUploadIntent(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/uploads/intent", wrapper.CreateUploadIntent)
}

type CreateUploadIntentRequestObject struct {
	Body *CreateUploadIntentJSONRequestBody
}

type CreateUploadIntentResponseObject interface {
	VisitCreateUploadIntentResponse(w http.ResponseWriter) error
}

type CreateUploadIntent201JSONResponse UploadIntent

func (response CreateUploadIntent201JSONResponse) VisitCreateUploadIntentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUploadIntent400JSONResponse Error

func (response CreateUploadIntent400JSONResponse) VisitCreateUploadIntentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateUploadIntent401JSONResponse Error

func (response CreateUploadIntent401JSONResponse) VisitCreateUploadIntentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateUploadIntent Create an upload intent
	// (POST /uploads/intent)
	CreateUploadIntent(ctx context.Context, request CreateUploadIntentRequestObject) (CreateUploadIntentResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// CreateUploadIntent operation middleware
func (sh *strictHandler) CreateUploadIntent(ctx *gin.Context) {
	var request CreateUploadIntentRequestObject

	var body CreateUploadIntentJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUploadIntent(ctx, request.(CreateUploadIntentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUploadIntent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateUploadIntentResponseObject); ok {
		if err := validResponse.VisitCreateUploadIntentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
