// Package leave provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package leave

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DecisionRequestDecision.
const (
	Approve DecisionRequestDecision = "approve"
	Reject  DecisionRequestDecision = "reject"
)

// Valid indicates whether the value is a known member of the DecisionRequestDecision enum.
func (e DecisionRequestDecision) Valid() bool {
	switch e {
	case Approve:
		return true
	case Reject:
		return true
	default:
		return false
	}
}

// Defines values for LeaveStatus.
const (
	Approved  LeaveStatus = "approved"
	Cancelled LeaveStatus = "cancelled"
	Pending   LeaveStatus = "pending"
	Rejected  LeaveStatus = "rejected"
)

// Valid indicates whether the value is a known member of the LeaveStatus enum.
func (e LeaveStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Cancelled:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Balance defines model for Balance.
type Balance struct {
	CarriedOverDays int    `json:"carried_over_days"`
	Code            string `json:"code"`
	LeaveTypeId     int64  `json:"leave_type_id"`
	Name            string `json:"name"`

	// PendingDays Pending requests starting that year; already held against the balance.
	PendingDays int `json:"pending_days"`
	QuotaDays   int `json:"quota_days"`

	// RemainingDays quota_days + carried_over_days - used_days - pending_days.
	RemainingDays int `json:"remaining_days"`

	// UsedDays Approved requests starting that year.
	UsedDays int `json:"used_days"`
	Year     int `json:"year"`
}

// DecisionRequest defines model for DecisionRequest.
type DecisionRequest struct {
	Decision DecisionRequestDecision `json:"decision"`

	// Note At most 500 characters.
	Note *string `json:"note,omitempty"`
}

// DecisionRequestDecision defines model for DecisionRequest.Decision.
type DecisionRequestDecision string

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Leave defines model for Leave.
type Leave struct {
	// AttachmentMime The attachment's sniffed type; absent when there is none.
	AttachmentMime *string    `json:"attachment_mime,omitempty"`
	CancelledAt    *time.Time `json:"cancelled_at,omitempty"`

	// CancelledBy Who withdrew it, when cancelled.
	CancelledBy *int64             `json:"cancelled_by,omitempty"`
	CreatedAt   time.Time          `json:"created_at"`
	EndDate     openapi_types.Date `json:"end_date"`
	Id          int64              `json:"id"`
	LeaveTypeId int64              `json:"leave_type_id"`
	Reason      string             `json:"reason"`
	ReviewNote  *string            `json:"review_note,omitempty"`
	ReviewedAt  *time.Time         `json:"reviewed_at,omitempty"`

	// ReviewedBy Absent when undecided, or approved on filing by a type that auto-approves.
	ReviewedBy *int64             `json:"reviewed_by,omitempty"`
	StartDate  openapi_types.Date `json:"start_date"`
	Status     LeaveStatus        `json:"status"`
	UserId     int64              `json:"user_id"`

	// WorkingDays The working days in the range when it was filed.
	WorkingDays int `json:"working_days"`
}

// LeaveStatus defines model for Leave.Status.
type LeaveStatus string

// LeaveRequest defines model for LeaveRequest.
type LeaveRequest struct {
	// AttachmentKey The key POST /uploads/intent returned, already uploaded.
	AttachmentKey *string `json:"attachment_key,omitempty"`

	// EndDate Inclusive, and at most 366 days after start_date.
	EndDate openapi_types.Date `json:"end_date"`

	// Reason At most 500 characters.
	Reason    string             `json:"reason"`
	StartDate openapi_types.Date `json:"start_date"`

	// Type A leave type's code.
	//
	// Example: annual
	Type string `json:"type"`
}

// LeaveType defines model for LeaveType.
type LeaveType struct {
	AttachmentRequiredFromDays *int   `json:"attachment_required_from_days,omitempty"`
	AutoApprove                bool   `json:"auto_approve"`
	Code                       string `json:"code"`
	Id                         int64  `json:"id"`
	IsPaid                     bool   `json:"is_paid"`
	MaxWorkingDaysPerRequest   *int   `json:"max_working_days_per_request,omitempty"`
	Name                       string `json:"name"`
	QuotaDaysPerYear           *int   `json:"quota_days_per_year,omitempty"`
}

// LeaveTypeRequest defines model for LeaveTypeRequest.
type LeaveTypeRequest struct {
	// AttachmentRequiredFromDays An attachment is required from this many working days on; absent for never.
	AttachmentRequiredFromDays *int `json:"attachment_required_from_days,omitempty"`
	AutoApprove                bool `json:"auto_approve"`

	// Code Lowercase letters, digits and underscores, starting with a letter; at most 50 characters.
	//
	// Example: annual
	Code   string `json:"code"`
	IsPaid bool   `json:"is_paid"`

	// MaxWorkingDaysPerRequest 1 to 366; absent for no cap.
	MaxWorkingDaysPerRequest *int `json:"max_working_days_per_request,omitempty"`

	// Name Example: Cuti Tahunan
	Name string `json:"name"`

	// QuotaDaysPerYear 0 to 366; absent for a type with no yearly quota.
	QuotaDaysPerYear *int `json:"quota_days_per_year,omitempty"`
}

// Quota defines model for Quota.
type Quota struct {
	CarriedOverDays int   `json:"carried_over_days"`
	LeaveTypeId     int64 `json:"leave_type_id"`
	QuotaDays       int   `json:"quota_days"`
	UserId          int64 `json:"user_id"`
	Year            int   `json:"year"`
}

// QuotaRequest defines model for QuotaRequest.
type QuotaRequest struct {
	// CarriedOverDays 0 to 366. Left out, the person keeps the carried-over days they have, 0 when none.
	CarriedOverDays *int  `json:"carried_over_days,omitempty"`
	LeaveTypeId     int64 `json:"leave_type_id"`

	// QuotaDays 0 to 366.
	QuotaDays int   `json:"quota_days"`
	UserId    int64 `json:"user_id"`
	Year      int   `json:"year"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetMyLeaveBalanceParams defines parameters for GetMyLeaveBalance.
type GetMyLeaveBalanceParams struct {
	// Year Defaults to the current year.
	Year *int `form:"year,omitempty" json:"year,omitempty"`
}

// SetLeaveQuotaJSONRequestBody defines body for SetLeaveQuota for application/json ContentType.
type SetLeaveQuotaJSONRequestBody = QuotaRequest

// CreateLeaveTypeJSONRequestBody defines body for CreateLeaveType for application/json ContentType.
type CreateLeaveTypeJSONRequestBody = LeaveTypeRequest

// UpdateLeaveTypeJSONRequestBody defines body for UpdateLeaveType for application/json ContentType.
type UpdateLeaveTypeJSONRequestBody = LeaveTypeRequest

// RequestLeaveJSONRequestBody defines body for RequestLeave for application/json ContentType.
type RequestLeaveJSONRequestBody = LeaveRequest

// DecideLeaveJSONRequestBody defines body for DecideLeave for application/json ContentType.
type DecideLeaveJSONRequestBody = DecisionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// SetLeaveQuota Set one person's quota for a type and year
	// (POST /leave-balances)
	SetLeaveQuota(c *gin.Context)
	// ListLeaveTypes List the leave types
	// (GET /leave-types)
	ListLeaveTypes(c *gin.Context)
	// CreateLeaveType Add a leave type
	// (POST /leave-types)
	CreateLeaveType(c *gin.Context)
	// DeleteLeaveType Remove a leave type
	// (DELETE /leave-types/{id})
	DeleteLeaveType(c *gin.Context, id int64)
	// UpdateLeaveType Replace a leave type
	// (PUT /leave-types/{id})
	UpdateLeaveType(c *gin.Context, id int64)
	// RequestLeave Request leave
	// (POST /leaves)
	RequestLeave(c *gin.Context)
	// ListMyLeaves List the caller's leave requests
	// (GET /leaves/me)
	ListMyLeaves(c *gin.Context)
	// GetMyLeaveBalance The caller's balance for every type with a yearly quota
	// (GET /leaves/me/balance)
	GetMyLeaveBalance(c *gin.Context, params GetMyLeaveBalanceParams)
	// ListPendingLeaves List leave requests waiting for the caller's decision
	// (GET /leaves/pending)
	ListPendingLeaves(c *gin.Context)
	// CancelLeave Withdraw a pending or approved leave request
	// (DELETE /leaves/{id})
	CancelLeave(c *gin.Context, id int64)
	// GetLeaveAttachment Redirect to a leave request's attachment
	// (GET /leaves/{id}/attachment)
	GetLeaveAttachment(c *gin.Context, id int64)
	// DecideLeave Approve or reject a pending leave request
	// (POST /leaves/{id}/decision)
	DecideLeave(c *gin.Context, id int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SetLeaveQuota operation middleware
func (siw *ServerInterfaceWrapper) SetLeaveQuota(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetLeaveQuota(c)
}

// ListLeaveTypes operation middleware
func (siw *ServerInterfaceWrapper) ListLeaveTypes(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListLeaveTypes(c)
}

// CreateLeaveType operation middleware
func (siw *ServerInterfaceWrapper) CreateLeaveType(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateLeaveType(c)
}

// DeleteLeaveType operation middleware
func (siw *ServerInterfaceWrapper) DeleteLeaveType(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLeaveType(c, id)
}

// UpdateLeaveType operation middleware
func (siw *ServerInterfaceWrapper) UpdateLeaveType(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateLeaveType(c, id)
}

// RequestLeave operation middleware
func (siw *ServerInterfaceWrapper) RequestLeave(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RequestLeave(c)
}

// ListMyLeaves operation middleware
func (siw *ServerInterfaceWrapper) ListMyLeaves(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyLeaves(c)
}

// GetMyLeaveBalance operation middleware
func (siw *ServerInterfaceWrapper) GetMyLeaveBalance(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMyLeaveBalanceParams

	// ------------- Optional query parameter "year" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "year", c.Request.URL.Query(), &params.Year, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter year: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyLeaveBalance(c, params)
}

// ListPendingLeaves operation middleware
func (siw *ServerInterfaceWrapper) ListPendingLeaves(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPendingLeaves(c)
}

// CancelLeave operation middleware
func (siw *ServerInterfaceWrapper) CancelLeave(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelLeave(c, id)
}

// GetLeaveAttachment operation middleware
func (siw *ServerInterfaceWrapper) GetLeaveAttachment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLeaveAttachment(c, id)
}

// DecideLeave operation middleware
func (siw *ServerInterfaceWrapper) DecideLeave(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DecideLeave(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/leaves", wrapper.RequestLeave)
	router.GET(options.BaseURL+"/leaves/me", wrapper.ListMyLeaves)
	router.GET(options.BaseURL+"/leaves/me/balance", wrapper.GetMyLeaveBalance)
	router.GET(options.BaseURL+"/leaves/pending", wrapper.ListPendingLeaves)
	router.DELETE(options.BaseURL+"/leaves/:id", wrapper.CancelLeave)
	router.POST(options.BaseURL+"/leaves/:id/decision", wrapper.DecideLeave)
	router.GET(options.BaseURL+"/leaves/:id/attachment", wrapper.GetLeaveAttachment)
	router.GET(options.BaseURL+"/leave-types", wrapper.ListLeaveTypes)
	router.POST(options.BaseURL+"/leave-types", wrapper.CreateLeaveType)
	router.DELETE(options.BaseURL+"/leave-types/:id", wrapper.DeleteLeaveType)
	router.PUT(options.BaseURL+"/leave-types/:id", wrapper.UpdateLeaveType)
	router.POST(options.BaseURL+"/leave-balances", wrapper.SetLeaveQuota)
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type SetLeaveQuotaRequestObject struct {
	Body *SetLeaveQuotaJSONRequestBody
}

type SetLeaveQuotaResponseObject interface {
	VisitSetLeaveQuotaResponse(w http.ResponseWriter) error
}

type SetLeaveQuota200JSONResponse Quota

func (response SetLeaveQuota200JSONResponse) VisitSetLeaveQuotaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SetLeaveQuota400JSONResponse struct{ BadRequestJSONResponse }

func (response SetLeaveQuota400JSONResponse) VisitSetLeaveQuotaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SetLeaveQuota401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SetLeaveQuota401JSONResponse) VisitSetLeaveQuotaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SetLeaveQuota403JSONResponse struct{ ForbiddenJSONResponse }

func (response SetLeaveQuota403JSONResponse) VisitSetLeaveQuotaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListLeaveTypesRequestObject struct {
}

type ListLeaveTypesResponseObject interface {
	VisitListLeaveTypesResponse(w http.ResponseWriter) error
}

type ListLeaveTypes200JSONResponse []LeaveType

func (response ListLeaveTypes200JSONResponse) VisitListLeaveTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListLeaveTypes401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListLeaveTypes401JSONResponse) VisitListLeaveTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLeaveTypeRequestObject struct {
	Body *CreateLeaveTypeJSONRequestBody
}

type CreateLeaveTypeResponseObject interface {
	VisitCreateLeaveTypeResponse(w http.ResponseWriter) error
}

type CreateLeaveType201JSONResponse LeaveType

func (response CreateLeaveType201JSONResponse) VisitCreateLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLeaveType400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateLeaveType400JSONResponse) VisitCreateLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLeaveType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateLeaveType401JSONResponse) VisitCreateLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLeaveType403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateLeaveType403JSONResponse) VisitCreateLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLeaveType409JSONResponse struct{ ConflictJSONResponse }

func (response CreateLeaveType409JSONResponse) VisitCreateLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteLeaveTypeRequestObject struct {
	Id int64 `json:"id"`
}

type DeleteLeaveTypeResponseObject interface {
	VisitDeleteLeaveTypeResponse(w http.ResponseWriter) error
}

type DeleteLeaveType204Response struct {
}

func (response DeleteLeaveType204Response) VisitDeleteLeaveTypeResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteLeaveType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteLeaveType401JSONResponse) VisitDeleteLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteLeaveType403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteLeaveType403JSONResponse) VisitDeleteLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteLeaveType404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteLeaveType404JSONResponse) VisitDeleteLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLeaveTypeRequestObject struct {
	Id   int64 `json:"id"`
	Body *UpdateLeaveTypeJSONRequestBody
}

type UpdateLeaveTypeResponseObject interface {
	VisitUpdateLeaveTypeResponse(w http.ResponseWriter) error
}

type UpdateLeaveType200JSONResponse LeaveType

func (response UpdateLeaveType200JSONResponse) VisitUpdateLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLeaveType400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateLeaveType400JSONResponse) VisitUpdateLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLeaveType401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateLeaveType401JSONResponse) VisitUpdateLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLeaveType403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateLeaveType403JSONResponse) VisitUpdateLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLeaveType404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateLeaveType404JSONResponse) VisitUpdateLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateLeaveType409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateLeaveType409JSONResponse) VisitUpdateLeaveTypeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type RequestLeaveRequestObject struct {
	Body *RequestLeaveJSONRequestBody
}

type RequestLeaveResponseObject interface {
	VisitRequestLeaveResponse(w http.ResponseWriter) error
}

type RequestLeave201JSONResponse Leave

func (response RequestLeave201JSONResponse) VisitRequestLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RequestLeave400JSONResponse struct{ BadRequestJSONResponse }

func (response RequestLeave400JSONResponse) VisitRequestLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RequestLeave401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RequestLeave401JSONResponse) VisitRequestLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RequestLeave403JSONResponse struct{ ForbiddenJSONResponse }

func (response RequestLeave403JSONResponse) VisitRequestLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RequestLeave404JSONResponse struct{ NotFoundJSONResponse }

func (response RequestLeave404JSONResponse) VisitRequestLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RequestLeave409JSONResponse struct{ ConflictJSONResponse }

func (response RequestLeave409JSONResponse) VisitRequestLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyLeavesRequestObject struct {
}

type ListMyLeavesResponseObject interface {
	VisitListMyLeavesResponse(w http.ResponseWriter) error
}

type ListMyLeaves200JSONResponse []Leave

func (response ListMyLeaves200JSONResponse) VisitListMyLeavesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyLeaves401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListMyLeaves401JSONResponse) VisitListMyLeavesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMyLeaveBalanceRequestObject struct {
	Params GetMyLeaveBalanceParams
}

type GetMyLeaveBalanceResponseObject interface {
	VisitGetMyLeaveBalanceResponse(w http.ResponseWriter) error
}

type GetMyLeaveBalance200JSONResponse []Balance

func (response GetMyLeaveBalance200JSONResponse) VisitGetMyLeaveBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMyLeaveBalance400JSONResponse struct{ BadRequestJSONResponse }

func (response GetMyLeaveBalance400JSONResponse) VisitGetMyLeaveBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMyLeaveBalance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMyLeaveBalance401JSONResponse) VisitGetMyLeaveBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListPendingLeavesRequestObject struct {
}

type ListPendingLeavesResponseObject interface {
	VisitListPendingLeavesResponse(w http.ResponseWriter) error
}

type ListPendingLeaves200JSONResponse []Leave

func (response ListPendingLeaves200JSONResponse) VisitListPendingLeavesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPendingLeaves401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListPendingLeaves401JSONResponse) VisitListPendingLeavesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListPendingLeaves403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListPendingLeaves403JSONResponse) VisitListPendingLeavesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CancelLeaveRequestObject struct {
	Id int64 `json:"id"`
}

type CancelLeaveResponseObject interface {
	VisitCancelLeaveResponse(w http.ResponseWriter) error
}

type CancelLeave204Response struct {
}

func (response CancelLeave204Response) VisitCancelLeaveResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CancelLeave401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CancelLeave401JSONResponse) VisitCancelLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CancelLeave403JSONResponse struct{ ForbiddenJSONResponse }

func (response CancelLeave403JSONResponse) VisitCancelLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CancelLeave404JSONResponse struct{ NotFoundJSONResponse }

func (response CancelLeave404JSONResponse) VisitCancelLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelLeave409JSONResponse struct{ ConflictJSONResponse }

func (response CancelLeave409JSONResponse) VisitCancelLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetLeaveAttachmentRequestObject struct {
	Id int64 `json:"id"`
}

type GetLeaveAttachmentResponseObject interface {
	VisitGetLeaveAttachmentResponse(w http.ResponseWriter) error
}

type GetLeaveAttachment302ResponseHeaders struct {
	Location string
}

type GetLeaveAttachment302Response struct {
	Headers GetLeaveAttachment302ResponseHeaders
}

func (response GetLeaveAttachment302Response) VisitGetLeaveAttachmentResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type GetLeaveAttachment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetLeaveAttachment401JSONResponse) VisitGetLeaveAttachmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetLeaveAttachment403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetLeaveAttachment403JSONResponse) VisitGetLeaveAttachmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetLeaveAttachment404JSONResponse struct{ NotFoundJSONResponse }

func (response GetLeaveAttachment404JSONResponse) VisitGetLeaveAttachmentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DecideLeaveRequestObject struct {
	Id   int64 `json:"id"`
	Body *DecideLeaveJSONRequestBody
}

type DecideLeaveResponseObject interface {
	VisitDecideLeaveResponse(w http.ResponseWriter) error
}

type DecideLeave200JSONResponse Leave

func (response DecideLeave200JSONResponse) VisitDecideLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DecideLeave400JSONResponse struct{ BadRequestJSONResponse }

func (response DecideLeave400JSONResponse) VisitDecideLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DecideLeave401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DecideLeave401JSONResponse) VisitDecideLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DecideLeave403JSONResponse struct{ ForbiddenJSONResponse }

func (response DecideLeave403JSONResponse) VisitDecideLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DecideLeave404JSONResponse struct{ NotFoundJSONResponse }

func (response DecideLeave404JSONResponse) VisitDecideLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DecideLeave409JSONResponse struct{ ConflictJSONResponse }

func (response DecideLeave409JSONResponse) VisitDecideLeaveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// SetLeaveQuota Set one person's quota for a type and year
	// (POST /leave-balances)
	SetLeaveQuota(ctx context.Context, request SetLeaveQuotaRequestObject) (SetLeaveQuotaResponseObject, error)
	// ListLeaveTypes List the leave types
	// (GET /leave-types)
	ListLeaveTypes(ctx context.Context, request ListLeaveTypesRequestObject) (ListLeaveTypesResponseObject, error)
	// CreateLeaveType Add a leave type
	// (POST /leave-types)
	CreateLeaveType(ctx context.Context, request CreateLeaveTypeRequestObject) (CreateLeaveTypeResponseObject, error)
	// DeleteLeaveType Remove a leave type
	// (DELETE /leave-types/{id})
	DeleteLeaveType(ctx context.Context, request DeleteLeaveTypeRequestObject) (DeleteLeaveTypeResponseObject, error)
	// UpdateLeaveType Replace a leave type
	// (PUT /leave-types/{id})
	UpdateLeaveType(ctx context.Context, request UpdateLeaveTypeRequestObject) (UpdateLeaveTypeResponseObject, error)
	// RequestLeave Request leave
	// (POST /leaves)
	RequestLeave(ctx context.Context, request RequestLeaveRequestObject) (RequestLeaveResponseObject, error)
	// ListMyLeaves List the caller's leave requests
	// (GET /leaves/me)
	ListMyLeaves(ctx context.Context, request ListMyLeavesRequestObject) (ListMyLeavesResponseObject, error)
	// GetMyLeaveBalance The caller's balance for every type with a yearly quota
	// (GET /leaves/me/balance)
	GetMyLeaveBalance(ctx context.Context, request GetMyLeaveBalanceRequestObject) (GetMyLeaveBalanceResponseObject, error)
	// ListPendingLeaves List leave requests waiting for the caller's decision
	// (GET /leaves/pending)
	ListPendingLeaves(ctx context.Context, request ListPendingLeavesRequestObject) (ListPendingLeavesResponseObject, error)
	// CancelLeave Withdraw a pending or approved leave request
	// (DELETE /leaves/{id})
	CancelLeave(ctx context.Context, request CancelLeaveRequestObject) (CancelLeaveResponseObject, error)
	// GetLeaveAttachment Redirect to a leave request's attachment
	// (GET /leaves/{id}/attachment)
	GetLeaveAttachment(ctx context.Context, request GetLeaveAttachmentRequestObject) (GetLeaveAttachmentResponseObject, error)
	// DecideLeave Approve or reject a pending leave request
	// (POST /leaves/{id}/decision)
	DecideLeave(ctx context.Context, request DecideLeaveRequestObject) (DecideLeaveResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// SetLeaveQuota operation middleware
func (sh *strictHandler) SetLeaveQuota(ctx *gin.Context) {
	var request SetLeaveQuotaRequestObject

	var body SetLeaveQuotaJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SetLeaveQuota(ctx, request.(SetLeaveQuotaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetLeaveQuota")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(SetLeaveQuotaResponseObject); ok {
		if err := validResponse.VisitSetLeaveQuotaResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListLeaveTypes operation middleware
func (sh *strictHandler) ListLeaveTypes(ctx *gin.Context) {
	var request ListLeaveTypesRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListLeaveTypes(ctx, request.(ListLeaveTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLeaveTypes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListLeaveTypesResponseObject); ok {
		if err := validResponse.VisitListLeaveTypesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateLeaveType operation middleware
func (sh *strictHandler) CreateLeaveType(ctx *gin.Context) {
	var request CreateLeaveTypeRequestObject

	var body CreateLeaveTypeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateLeaveType(ctx, request.(CreateLeaveTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateLeaveType")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateLeaveTypeResponseObject); ok {
		if err := validResponse.VisitCreateLeaveTypeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteLeaveType operation middleware
func (sh *strictHandler) DeleteLeaveType(ctx *gin.Context, id int64) {
	var request DeleteLeaveTypeRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteLeaveType(ctx, request.(DeleteLeaveTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteLeaveType")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteLeaveTypeResponseObject); ok {
		if err := validResponse.VisitDeleteLeaveTypeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateLeaveType operation middleware
func (sh *strictHandler) UpdateLeaveType(ctx *gin.Context, id int64) {
	var request UpdateLeaveTypeRequestObject

	request.Id = id

	var body UpdateLeaveTypeJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateLeaveType(ctx, request.(UpdateLeaveTypeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateLeaveType")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateLeaveTypeResponseObject); ok {
		if err := validResponse.VisitUpdateLeaveTypeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestLeave operation middleware
func (sh *strictHandler) RequestLeave(ctx *gin.Context) {
	var request RequestLeaveRequestObject

	var body RequestLeaveJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RequestLeave(ctx, request.(RequestLeaveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestLeave")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RequestLeaveResponseObject); ok {
		if err := validResponse.VisitRequestLeaveResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMyLeaves operation middleware
func (sh *strictHandler) ListMyLeaves(ctx *gin.Context) {
	var request ListMyLeavesRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListMyLeaves(ctx, request.(ListMyLeavesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMyLeaves")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListMyLeavesResponseObject); ok {
		if err := validResponse.VisitListMyLeavesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMyLeaveBalance operation middleware
func (sh *strictHandler) GetMyLeaveBalance(ctx *gin.Context, params GetMyLeaveBalanceParams) {
	var request GetMyLeaveBalanceRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMyLeaveBalance(ctx, request.(GetMyLeaveBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMyLeaveBalance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetMyLeaveBalanceResponseObject); ok {
		if err := validResponse.VisitGetMyLeaveBalanceResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPendingLeaves operation middleware
func (sh *strictHandler) ListPendingLeaves(ctx *gin.Context) {
	var request ListPendingLeavesRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListPendingLeaves(ctx, request.(ListPendingLeavesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPendingLeaves")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListPendingLeavesResponseObject); ok {
		if err := validResponse.VisitListPendingLeavesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelLeave operation middleware
func (sh *strictHandler) CancelLeave(ctx *gin.Context, id int64) {
	var request CancelLeaveRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CancelLeave(ctx, request.(CancelLeaveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelLeave")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CancelLeaveResponseObject); ok {
		if err := validResponse.VisitCancelLeaveResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLeaveAttachment operation middleware
func (sh *strictHandler) GetLeaveAttachment(ctx *gin.Context, id int64) {
	var request GetLeaveAttachmentRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLeaveAttachment(ctx, request.(GetLeaveAttachmentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLeaveAttachment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetLeaveAttachmentResponseObject); ok {
		if err := validResponse.VisitGetLeaveAttachmentResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DecideLeave operation middleware
func (sh *strictHandler) DecideLeave(ctx *gin.Context, id int64) {
	var request DecideLeaveRequestObject

	request.Id = id

	var body DecideLeaveJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DecideLeave(ctx, request.(DecideLeaveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DecideLeave")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DecideLeaveResponseObject); ok {
		if err := validResponse.VisitDecideLeaveResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
