// Package attendance provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package attendance

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CorrectionStatus.
const (
	Approved  CorrectionStatus = "approved"
	Cancelled CorrectionStatus = "cancelled"
	Pending   CorrectionStatus = "pending"
	Rejected  CorrectionStatus = "rejected"
)

// Valid indicates whether the value is a known member of the CorrectionStatus enum.
func (e CorrectionStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Cancelled:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for DecisionRequestDecision.
const (
	Approve DecisionRequestDecision = "approve"
	Reject  DecisionRequestDecision = "reject"
)

// Valid indicates whether the value is a known member of the DecisionRequestDecision enum.
func (e DecisionRequestDecision) Valid() bool {
	switch e {
	case Approve:
		return true
	case Reject:
		return true
	default:
		return false
	}
}

// Defines values for PresenceStatus.
const (
	Absent  PresenceStatus = "absent"
	Holiday PresenceStatus = "holiday"
	Late    PresenceStatus = "late"
	NotYet  PresenceStatus = "not_yet"
	Off     PresenceStatus = "off"
	OnLeave PresenceStatus = "on_leave"
	Present PresenceStatus = "present"
)

// Valid indicates whether the value is a known member of the PresenceStatus enum.
func (e PresenceStatus) Valid() bool {
	switch e {
	case Absent:
		return true
	case Holiday:
		return true
	case Late:
		return true
	case NotYet:
		return true
	case Off:
		return true
	case OnLeave:
		return true
	case Present:
		return true
	default:
		return false
	}
}

// Defines values for GetAttendancePhotoParamsSide.
const (
	In  GetAttendancePhotoParamsSide = "in"
	Out GetAttendancePhotoParamsSide = "out"
)

// Valid indicates whether the value is a known member of the GetAttendancePhotoParamsSide enum.
func (e GetAttendancePhotoParamsSide) Valid() bool {
	switch e {
	case In:
		return true
	case Out:
		return true
	default:
		return false
	}
}

// Attendance defines model for Attendance.
type Attendance struct {
	CheckIn              *Evidence  `json:"check_in,omitempty"`
	CheckInAt            time.Time  `json:"check_in_at"`
	CheckOut             *Evidence  `json:"check_out,omitempty"`
	CheckOutAt           *time.Time `json:"check_out_at,omitempty"`
	DailyReport          *string    `json:"daily_report,omitempty"`
	DailyReportUpdatedAt *time.Time `json:"daily_report_updated_at,omitempty"`
	EarlyLeaveMinutes    int        `json:"early_leave_minutes"`
	Id                   int64      `json:"id"`

	// LateMinutes Whole minutes past the shift's start, less its grace.
	LateMinutes int `json:"late_minutes"`

	// ScheduleId The schedule in force at check-in; absent on a day with no hours.
	ScheduleId *int64             `json:"schedule_id,omitempty"`
	UserId     int64              `json:"user_id"`
	WorkDate   openapi_types.Date `json:"work_date"`
}

// Correction defines model for Correction.
type Correction struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`

	// OldCheckInAt What the attendance held before approval; absent when there was no attendance.
	OldCheckInAt       *time.Time         `json:"old_check_in_at,omitempty"`
	OldCheckOutAt      *time.Time         `json:"old_check_out_at,omitempty"`
	ProposedCheckInAt  *time.Time         `json:"proposed_check_in_at,omitempty"`
	ProposedCheckOutAt *time.Time         `json:"proposed_check_out_at,omitempty"`
	Reason             string             `json:"reason"`
	RequestedBy        int64              `json:"requested_by"`
	ReviewNote         *string            `json:"review_note,omitempty"`
	ReviewedAt         *time.Time         `json:"reviewed_at,omitempty"`
	ReviewedBy         *int64             `json:"reviewed_by,omitempty"`
	Status             CorrectionStatus   `json:"status"`
	UserId             int64              `json:"user_id"`
	WorkDate           openapi_types.Date `json:"work_date"`
}

// CorrectionStatus defines model for Correction.Status.
type CorrectionStatus string

// CorrectionRequest defines model for CorrectionRequest.
type CorrectionRequest struct {
	ProposedCheckInAt *time.Time `json:"proposed_check_in_at,omitempty"`

	// ProposedCheckOutAt At least one of the two times is required.
	ProposedCheckOutAt *time.Time `json:"proposed_check_out_at,omitempty"`

	// Reason At most 500 characters.
	Reason string `json:"reason"`

	// UserId hr_admin only, to file for someone else. Defaults to the caller.
	UserId   *int64             `json:"user_id,omitempty"`
	WorkDate openapi_types.Date `json:"work_date"`
}

// DailyReportRequest defines model for DailyReportRequest.
type DailyReportRequest struct {
	// Content At most 5000 characters.
	Content  string             `json:"content"`
	WorkDate openapi_types.Date `json:"work_date"`
}

// DecisionRequest defines model for DecisionRequest.
type DecisionRequest struct {
	Decision DecisionRequestDecision `json:"decision"`

	// Note At most 500 characters.
	Note *string `json:"note,omitempty"`
}

// DecisionRequestDecision defines model for DecisionRequest.Decision.
type DecisionRequestDecision string

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Evidence defines model for Evidence.
type Evidence struct {
	AccuracyM    float64 `json:"accuracy_m"`
	Lat          float64 `json:"lat"`
	Lng          float64 `json:"lng"`
	MockLocation bool    `json:"mock_location"`

	// OfficeLocationId The office the point falls inside, or else the nearest one.
	OfficeLocationId *int64 `json:"office_location_id,omitempty"`
	WithinGeofence   bool   `json:"within_geofence"`
}

// MarkRequest defines model for MarkRequest.
type MarkRequest struct {
	// AccuracyM The phone's reported accuracy radius, in meters.
	//
	// Example: 12
	AccuracyM float64 `json:"accuracy_m"`

	// Lat Example: -6.2088
	Lat float64 `json:"lat"`

	// Lng Example: 106.8456
	Lng float64 `json:"lng"`

	// MockLocation What Android reports; stored for the supervisor, never trusted as proof.
	MockLocation bool `json:"mock_location"`

	// PhotoKey The key POST /uploads/intent returned, already uploaded.
	PhotoKey string `json:"photo_key"`
}

// Presence defines model for Presence.
type Presence struct {
	Attendance   *Attendance `json:"attendance,omitempty"`
	DepartmentId *int64      `json:"department_id,omitempty"`
	FullName     string      `json:"full_name"`

	// Status present or late with an attendance; otherwise on_leave (approved leave covers the date), holiday, off
	// (not a working day), not_yet (the shift and its grace have not started), or absent.
	Status PresenceStatus `json:"status"`
	UserId int64          `json:"user_id"`
}

// PresenceStatus present or late with an attendance; otherwise on_leave (approved leave covers the date), holiday, off
// (not a working day), not_yet (the shift and its grace have not started), or absent.
type PresenceStatus string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListMyAttendanceParams defines parameters for ListMyAttendance.
type ListMyAttendanceParams struct {
	From openapi_types.Date `form:"from" json:"from"`

	// To Inclusive, and at most 366 days after from.
	To openapi_types.Date `form:"to" json:"to"`
}

// GetWhosInParams defines parameters for GetWhosIn.
type GetWhosInParams struct {
	Date openapi_types.Date `form:"date" json:"date"`
}

// GetAttendancePhotoParamsSide defines parameters for GetAttendancePhoto.
type GetAttendancePhotoParamsSide string

// CheckInJSONRequestBody defines body for CheckIn for application/json ContentType.
type CheckInJSONRequestBody = MarkRequest

// CheckOutJSONRequestBody defines body for CheckOut for application/json ContentType.
type CheckOutJSONRequestBody = MarkRequest

// RequestCorrectionJSONRequestBody defines body for RequestCorrection for application/json ContentType.
type RequestCorrectionJSONRequestBody = CorrectionRequest

// DecideCorrectionJSONRequestBody defines body for DecideCorrection for application/json ContentType.
type DecideCorrectionJSONRequestBody = DecisionRequest

// SaveDailyReportJSONRequestBody defines body for SaveDailyReport for application/json ContentType.
type SaveDailyReportJSONRequestBody = DailyReportRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CheckIn Check in
	// (POST /attendance/check-in)
	CheckIn(c *gin.Context)
	// CheckOut Check out
	// (POST /attendance/check-out)
	CheckOut(c *gin.Context)
	// RequestCorrection Ask for a day's times to be corrected
	// (POST /attendance/corrections)
	RequestCorrection(c *gin.Context)
	// ListMyCorrections List corrections to the caller's attendance
	// (GET /attendance/corrections/me)
	ListMyCorrections(c *gin.Context)
	// ListPendingCorrections List corrections waiting for the caller's decision
	// (GET /attendance/corrections/pending)
	ListPendingCorrections(c *gin.Context)
	// CancelCorrection Withdraw a pending correction
	// (DELETE /attendance/corrections/{id})
	CancelCorrection(c *gin.Context, id int64)
	// DecideCorrection Approve or reject a pending correction
	// (POST /attendance/corrections/{id}/decision)
	DecideCorrection(c *gin.Context, id int64)
	// ListMyAttendance List the caller's attendance
	// (GET /attendance/me)
	ListMyAttendance(c *gin.Context, params ListMyAttendanceParams)
	// SaveDailyReport Write the daily report for a work date
	// (PUT /attendance/me/daily-report)
	SaveDailyReport(c *gin.Context)
	// GetWhosIn Who has and has not come in on a date
	// (GET /attendance/whos-in)
	GetWhosIn(c *gin.Context, params GetWhosInParams)
	// GetAttendancePhoto Redirect to a check-in or check-out selfie
	// (GET /attendance/{id}/photo/{side})
	GetAttendancePhoto(c *gin.Context, id int64, side GetAttendancePhotoParamsSide)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CheckIn operation middleware
func (siw *ServerInterfaceWrapper) CheckIn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CheckIn(c)
}

// CheckOut operation middleware
func (siw *ServerInterfaceWrapper) CheckOut(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CheckOut(c)
}

// RequestCorrection operation middleware
func (siw *ServerInterfaceWrapper) RequestCorrection(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RequestCorrection(c)
}

// ListMyCorrections operation middleware
func (siw *ServerInterfaceWrapper) ListMyCorrections(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyCorrections(c)
}

// ListPendingCorrections operation middleware
func (siw *ServerInterfaceWrapper) ListPendingCorrections(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPendingCorrections(c)
}

// CancelCorrection operation middleware
func (siw *ServerInterfaceWrapper) CancelCorrection(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelCorrection(c, id)
}

// DecideCorrection operation middleware
func (siw *ServerInterfaceWrapper) DecideCorrection(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DecideCorrection(c, id)
}

// ListMyAttendance operation middleware
func (siw *ServerInterfaceWrapper) ListMyAttendance(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMyAttendanceParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyAttendance(c, params)
}

// SaveDailyReport operation middleware
func (siw *ServerInterfaceWrapper) SaveDailyReport(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SaveDailyReport(c)
}

// GetWhosIn operation middleware
func (siw *ServerInterfaceWrapper) GetWhosIn(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWhosInParams

	// ------------- Required query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "date", c.Request.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter date: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWhosIn(c, params)
}

// GetAttendancePhoto operation middleware
func (siw *ServerInterfaceWrapper) GetAttendancePhoto(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "side" -------------
	var side GetAttendancePhotoParamsSide

	err = runtime.BindStyledParameterWithOptions("simple", "side", c.Param("side"), &side, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter side: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAttendancePhoto(c, id, side)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/attendance/check-in", wrapper.CheckIn)
	router.POST(options.BaseURL+"/attendance/check-out", wrapper.CheckOut)
	router.GET(options.BaseURL+"/attendance/me", wrapper.ListMyAttendance)
	router.PUT(options.BaseURL+"/attendance/me/daily-report", wrapper.SaveDailyReport)
	router.GET(options.BaseURL+"/attendance/:id/photo/:side", wrapper.GetAttendancePhoto)
	router.GET(options.BaseURL+"/attendance/whos-in", wrapper.GetWhosIn)
	router.POST(options.BaseURL+"/attendance/corrections", wrapper.RequestCorrection)
	router.GET(options.BaseURL+"/attendance/corrections/me", wrapper.ListMyCorrections)
	router.GET(options.BaseURL+"/attendance/corrections/pending", wrapper.ListPendingCorrections)
	router.DELETE(options.BaseURL+"/attendance/corrections/:id", wrapper.CancelCorrection)
	router.POST(options.BaseURL+"/attendance/corrections/:id/decision", wrapper.DecideCorrection)
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type CheckInRequestObject struct {
	Body *CheckInJSONRequestBody
}

type CheckInResponseObject interface {
	VisitCheckInResponse(w http.ResponseWriter) error
}

type CheckIn201JSONResponse Attendance

func (response CheckIn201JSONResponse) VisitCheckInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CheckIn400JSONResponse struct{ BadRequestJSONResponse }

func (response CheckIn400JSONResponse) VisitCheckInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CheckIn401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CheckIn401JSONResponse) VisitCheckInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CheckIn403JSONResponse struct{ ForbiddenJSONResponse }

func (response CheckIn403JSONResponse) VisitCheckInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CheckIn404JSONResponse struct{ NotFoundJSONResponse }

func (response CheckIn404JSONResponse) VisitCheckInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CheckIn409JSONResponse struct{ ConflictJSONResponse }

func (response CheckIn409JSONResponse) VisitCheckInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CheckOutRequestObject struct {
	Body *CheckOutJSONRequestBody
}

type CheckOutResponseObject interface {
	VisitCheckOutResponse(w http.ResponseWriter) error
}

type CheckOut200JSONResponse Attendance

func (response CheckOut200JSONResponse) VisitCheckOutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CheckOut400JSONResponse struct{ BadRequestJSONResponse }

func (response CheckOut400JSONResponse) VisitCheckOutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CheckOut401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CheckOut401JSONResponse) VisitCheckOutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CheckOut403JSONResponse struct{ ForbiddenJSONResponse }

func (response CheckOut403JSONResponse) VisitCheckOutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RequestCorrectionRequestObject struct {
	Body *RequestCorrectionJSONRequestBody
}

type RequestCorrectionResponseObject interface {
	VisitRequestCorrectionResponse(w http.ResponseWriter) error
}

type RequestCorrection201JSONResponse Correction

func (response RequestCorrection201JSONResponse) VisitRequestCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RequestCorrection400JSONResponse struct{ BadRequestJSONResponse }

func (response RequestCorrection400JSONResponse) VisitRequestCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RequestCorrection401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RequestCorrection401JSONResponse) VisitRequestCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RequestCorrection403JSONResponse struct{ ForbiddenJSONResponse }

func (response RequestCorrection403JSONResponse) VisitRequestCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RequestCorrection409JSONResponse struct{ ConflictJSONResponse }

func (response RequestCorrection409JSONResponse) VisitRequestCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyCorrectionsRequestObject struct {
}

type ListMyCorrectionsResponseObject interface {
	VisitListMyCorrectionsResponse(w http.ResponseWriter) error
}

type ListMyCorrections200JSONResponse []Correction

func (response ListMyCorrections200JSONResponse) VisitListMyCorrectionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyCorrections401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListMyCorrections401JSONResponse) VisitListMyCorrectionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListPendingCorrectionsRequestObject struct {
}

type ListPendingCorrectionsResponseObject interface {
	VisitListPendingCorrectionsResponse(w http.ResponseWriter) error
}

type ListPendingCorrections200JSONResponse []Correction

func (response ListPendingCorrections200JSONResponse) VisitListPendingCorrectionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPendingCorrections401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListPendingCorrections401JSONResponse) VisitListPendingCorrectionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListPendingCorrections403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListPendingCorrections403JSONResponse) VisitListPendingCorrectionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CancelCorrectionRequestObject struct {
	Id int64 `json:"id"`
}

type CancelCorrectionResponseObject interface {
	VisitCancelCorrectionResponse(w http.ResponseWriter) error
}

type CancelCorrection204Response struct {
}

func (response CancelCorrection204Response) VisitCancelCorrectionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CancelCorrection401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CancelCorrection401JSONResponse) VisitCancelCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CancelCorrection403JSONResponse struct{ ForbiddenJSONResponse }

func (response CancelCorrection403JSONResponse) VisitCancelCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CancelCorrection404JSONResponse struct{ NotFoundJSONResponse }

func (response CancelCorrection404JSONResponse) VisitCancelCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelCorrection409JSONResponse struct{ ConflictJSONResponse }

func (response CancelCorrection409JSONResponse) VisitCancelCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCorrectionRequestObject struct {
	Id   int64 `json:"id"`
	Body *DecideCorrectionJSONRequestBody
}

type DecideCorrectionResponseObject interface {
	VisitDecideCorrectionResponse(w http.ResponseWriter) error
}

type DecideCorrection200JSONResponse Correction

func (response DecideCorrection200JSONResponse) VisitDecideCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCorrection400JSONResponse struct{ BadRequestJSONResponse }

func (response DecideCorrection400JSONResponse) VisitDecideCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCorrection401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DecideCorrection401JSONResponse) VisitDecideCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCorrection403JSONResponse struct{ ForbiddenJSONResponse }

func (response DecideCorrection403JSONResponse) VisitDecideCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCorrection404JSONResponse struct{ NotFoundJSONResponse }

func (response DecideCorrection404JSONResponse) VisitDecideCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DecideCorrection409JSONResponse struct{ ConflictJSONResponse }

func (response DecideCorrection409JSONResponse) VisitDecideCorrectionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyAttendanceRequestObject struct {
	Params ListMyAttendanceParams
}

type ListMyAttendanceResponseObject interface {
	VisitListMyAttendanceResponse(w http.ResponseWriter) error
}

type ListMyAttendance200JSONResponse []Attendance

func (response ListMyAttendance200JSONResponse) VisitListMyAttendanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyAttendance400JSONResponse struct{ BadRequestJSONResponse }

func (response ListMyAttendance400JSONResponse) VisitListMyAttendanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListMyAttendance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListMyAttendance401JSONResponse) VisitListMyAttendanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SaveDailyReportRequestObject struct {
	Body *SaveDailyReportJSONRequestBody
}

type SaveDailyReportResponseObject interface {
	VisitSaveDailyReportResponse(w http.ResponseWriter) error
}

type SaveDailyReport200JSONResponse Attendance

func (response SaveDailyReport200JSONResponse) VisitSaveDailyReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SaveDailyReport400JSONResponse struct{ BadRequestJSONResponse }

func (response SaveDailyReport400JSONResponse) VisitSaveDailyReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SaveDailyReport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SaveDailyReport401JSONResponse) VisitSaveDailyReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SaveDailyReport404JSONResponse struct{ NotFoundJSONResponse }

func (response SaveDailyReport404JSONResponse) VisitSaveDailyReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetWhosInRequestObject struct {
	Params GetWhosInParams
}

type GetWhosInResponseObject interface {
	VisitGetWhosInResponse(w http.ResponseWriter) error
}

type GetWhosIn200JSONResponse []Presence

func (response GetWhosIn200JSONResponse) VisitGetWhosInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetWhosIn400JSONResponse struct{ BadRequestJSONResponse }

func (response GetWhosIn400JSONResponse) VisitGetWhosInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetWhosIn401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetWhosIn401JSONResponse) VisitGetWhosInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetWhosIn403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetWhosIn403JSONResponse) VisitGetWhosInResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendancePhotoRequestObject struct {
	Id   int64                        `json:"id"`
	Side GetAttendancePhotoParamsSide `json:"side"`
}

type GetAttendancePhotoResponseObject interface {
	VisitGetAttendancePhotoResponse(w http.ResponseWriter) error
}

type GetAttendancePhoto302ResponseHeaders struct {
	Location string
}

type GetAttendancePhoto302Response struct {
	Headers GetAttendancePhoto302ResponseHeaders
}

func (response GetAttendancePhoto302Response) VisitGetAttendancePhotoResponse(w http.ResponseWriter) error {
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type GetAttendancePhoto400JSONResponse struct{ BadRequestJSONResponse }

func (response GetAttendancePhoto400JSONResponse) VisitGetAttendancePhotoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendancePhoto401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAttendancePhoto401JSONResponse) VisitGetAttendancePhotoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendancePhoto403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAttendancePhoto403JSONResponse) VisitGetAttendancePhotoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetAttendancePhoto404JSONResponse struct{ NotFoundJSONResponse }

func (response GetAttendancePhoto404JSONResponse) VisitGetAttendancePhotoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CheckIn Check in
	// (POST /attendance/check-in)
	CheckIn(ctx context.Context, request CheckInRequestObject) (CheckInResponseObject, error)
	// CheckOut Check out
	// (POST /attendance/check-out)
	CheckOut(ctx context.Context, request CheckOutRequestObject) (CheckOutResponseObject, error)
	// RequestCorrection Ask for a day's times to be corrected
	// (POST /attendance/corrections)
	RequestCorrection(ctx context.Context, request RequestCorrectionRequestObject) (RequestCorrectionResponseObject, error)
	// ListMyCorrections List corrections to the caller's attendance
	// (GET /attendance/corrections/me)
	ListMyCorrections(ctx context.Context, request ListMyCorrectionsRequestObject) (ListMyCorrectionsResponseObject, error)
	// ListPendingCorrections List corrections waiting for the caller's decision
	// (GET /attendance/corrections/pending)
	ListPendingCorrections(ctx context.Context, request ListPendingCorrectionsRequestObject) (ListPendingCorrectionsResponseObject, error)
	// CancelCorrection Withdraw a pending correction
	// (DELETE /attendance/corrections/{id})
	CancelCorrection(ctx context.Context, request CancelCorrectionRequestObject) (CancelCorrectionResponseObject, error)
	// DecideCorrection Approve or reject a pending correction
	// (POST /attendance/corrections/{id}/decision)
	DecideCorrection(ctx context.Context, request DecideCorrectionRequestObject) (DecideCorrectionResponseObject, error)
	// ListMyAttendance List the caller's attendance
	// (GET /attendance/me)
	ListMyAttendance(ctx context.Context, request ListMyAttendanceRequestObject) (ListMyAttendanceResponseObject, error)
	// SaveDailyReport Write the daily report for a work date
	// (PUT /attendance/me/daily-report)
	SaveDailyReport(ctx context.Context, request SaveDailyReportRequestObject) (SaveDailyReportResponseObject, error)
	// GetWhosIn Who has and has not come in on a date
	// (GET /attendance/whos-in)
	GetWhosIn(ctx context.Context, request GetWhosInRequestObject) (GetWhosInResponseObject, error)
	// GetAttendancePhoto Redirect to a check-in or check-out selfie
	// (GET /attendance/{id}/photo/{side})
	GetAttendancePhoto(ctx context.Context, request GetAttendancePhotoRequestObject) (GetAttendancePhotoResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// CheckIn operation middleware
func (sh *strictHandler) CheckIn(ctx *gin.Context) {
	var request CheckInRequestObject

	var body CheckInJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CheckIn(ctx, request.(CheckInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CheckInResponseObject); ok {
		if err := validResponse.VisitCheckInResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CheckOut operation middleware
func (sh *strictHandler) CheckOut(ctx *gin.Context) {
	var request CheckOutRequestObject

	var body CheckOutJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CheckOut(ctx, request.(CheckOutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckOut")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CheckOutResponseObject); ok {
		if err := validResponse.VisitCheckOutResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestCorrection operation middleware
func (sh *strictHandler) RequestCorrection(ctx *gin.Context) {
	var request RequestCorrectionRequestObject

	var body RequestCorrectionJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RequestCorrection(ctx, request.(RequestCorrectionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestCorrection")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RequestCorrectionResponseObject); ok {
		if err := validResponse.VisitRequestCorrectionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMyCorrections operation middleware
func (sh *strictHandler) ListMyCorrections(ctx *gin.Context) {
	var request ListMyCorrectionsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListMyCorrections(ctx, request.(ListMyCorrectionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMyCorrections")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListMyCorrectionsResponseObject); ok {
		if err := validResponse.VisitListMyCorrectionsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPendingCorrections operation middleware
func (sh *strictHandler) ListPendingCorrections(ctx *gin.Context) {
	var request ListPendingCorrectionsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListPendingCorrections(ctx, request.(ListPendingCorrectionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPendingCorrections")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListPendingCorrectionsResponseObject); ok {
		if err := validResponse.VisitListPendingCorrectionsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelCorrection operation middleware
func (sh *strictHandler) CancelCorrection(ctx *gin.Context, id int64) {
	var request CancelCorrectionRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CancelCorrection(ctx, request.(CancelCorrectionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelCorrection")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CancelCorrectionResponseObject); ok {
		if err := validResponse.VisitCancelCorrectionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DecideCorrection operation middleware
func (sh *strictHandler) DecideCorrection(ctx *gin.Context, id int64) {
	var request DecideCorrectionRequestObject

	request.Id = id

	var body DecideCorrectionJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DecideCorrection(ctx, request.(DecideCorrectionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DecideCorrection")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DecideCorrectionResponseObject); ok {
		if err := validResponse.VisitDecideCorrectionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMyAttendance operation middleware
func (sh *strictHandler) ListMyAttendance(ctx *gin.Context, params ListMyAttendanceParams) {
	var request ListMyAttendanceRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListMyAttendance(ctx, request.(ListMyAttendanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMyAttendance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListMyAttendanceResponseObject); ok {
		if err := validResponse.VisitListMyAttendanceResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SaveDailyReport operation middleware
func (sh *strictHandler) SaveDailyReport(ctx *gin.Context) {
	var request SaveDailyReportRequestObject

	var body SaveDailyReportJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SaveDailyReport(ctx, request.(SaveDailyReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SaveDailyReport")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(SaveDailyReportResponseObject); ok {
		if err := validResponse.VisitSaveDailyReportResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWhosIn operation middleware
func (sh *strictHandler) GetWhosIn(ctx *gin.Context, params GetWhosInParams) {
	var request GetWhosInRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWhosIn(ctx, request.(GetWhosInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWhosIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetWhosInResponseObject); ok {
		if err := validResponse.VisitGetWhosInResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAttendancePhoto operation middleware
func (sh *strictHandler) GetAttendancePhoto(ctx *gin.Context, id int64, side GetAttendancePhotoParamsSide) {
	var request GetAttendancePhotoRequestObject

	request.Id = id
	request.Side = side

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAttendancePhoto(ctx, request.(GetAttendancePhotoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAttendancePhoto")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetAttendancePhotoResponseObject); ok {
		if err := validResponse.VisitGetAttendancePhotoResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
